- name: Create Datacenter
  vmware_datacenter:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter_name }}'
    state: present
    validate_certs: no

- name: Create a VM folder on given Datacenter
  vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ datacenter_name }}'
    folder_name: my_vm
    folder_type: vm
    state: present
    validate_certs: no

- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter_name }}'
    cluster_name: cluster
    validate_certs: no

- name: Add ESXi Hosts to vCenter
  vmware_host:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter_name }}'
    cluster_name: cluster
    esxi_hostname: '{{ hostvars[item].ansible_host }}'
    esxi_username: 'root'
    esxi_password: 'root'
    state: present
    validate_certs: no
  with_items: "{{ groups['all'] }}"


