- name: Export the NFS share
  lineinfile:
    path: /etc/exports
    line: "/srv/esx_lab {{ vsphere_lab_network_prefix }}.0/255.255.255.0(rw,anonuid=1000,anongid=1000)"
    regex: '^/srv/esx_lab'
  notify: reload NFS server
  become: true

- name: Ensure NFS server is running
  systemd:
    name: nfs-server
    state: started

- name: Mount VMFS datastores to ESXi
  vmware_host_datastore:
      hostname: '{{ hostvars["esxi-vcenter"].ansible_host }}'
      username: root
      password: root
      datastore_name: '{{ datastore_name }}'
      datastore_type: nfs
      nfs_server: "{{ vsphere_lab_nfs_server }}"
      nfs_path: "{{ vsphere_lab_nfs_path }}"
      nfs_ro: no
      esxi_hostname: 'esxi-vcenter'
      state: present
      validate_certs: no

