- name: reimport the vCenter VM
  command: 'vim-cmd solo/registervm /vmfs/volumes/esx_lab/vCenter-Server-Appliance/vCenter-Server-Appliance.vmx'
  delegate_to: esxi-vcenter
  register: reimport_result
  failed_when:
  - "'vim.fault.AlreadyExists' not in reimport_result.stdout"
  - "reimport_result.rc != 0"

- name: Set the state of a virtual machine to poweroff
  vmware_guest_powerstate:
    hostname: '{{ hostvars["esxi-vcenter"].ansible_host }}'
    username: root
    password: root
    validate_certs: no
    #    folder: /"{{ datacenter_name }}"/vm/my_folder
    name: "vCenter-Server-Appliance"
    state: powered-on

- name: 'Wait for the VSphere to be reachable (=~ 180s)'
  uri:
    method: HEAD
    validate_certs: no
    url: 'https://{{ vcenter_hostname }}'
    register: uri_result
    until: uri_result.status != 200
    retries: 180
    delay: 3
