- name: Create a VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    folder: 'my_vm'
    cluster: cluster
    name: test_vm_0001
    state: poweredon
    guest_id: debian8_64Guest
    disk:
    - size_gb: 1
      type: thin
      datastore: '{{ datastore_name }}'
    cdrom:
      type: iso
      iso_path: "[{{ datastore_name }}] isos/alpine-virt-3.9.2-x86_64.iso"
    hardware:
      memory_mb: 512
      num_cpus: 1
      scsi: paravirtual
    wait_for_ip_address: yes
    validate_certs: no
