VCSA_iso: "{{ lookup('env','HOME') }}/Downloads/VMware-VCSA-all-6.7.0-11726888.iso"
vcenter_hostname: '192.168.123.90'
vcenter_username: 'administrator@vsphere.local'
vcenter_password: '!234AaAa56'
datacenter_name: dc_ansible
datacenter_folder_name: vm1
datastore_name: esx_lab
nfs_dir: /srv/esx_lab
nfs_export: /etc/exports
